image: python:3.4-alpine

stages:
-   check
-   test

before_script:
-   pip install -r requirements.txt
-   pip install -r requirements-testing.txt

pytest:
    script:
    -   ENV_NAME=testing ASYNC_TEST_TIMEOUT=15 coverage run --source="Charon" -m pytest
    -   coverage report --show-missing  --fail-under=49
    coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%.*/'
